create table if not exists public.articles (
    id bigint generated by default as identity primary key,
    title text not null,
    category text not null default 'artikel',
    category_label text,
    tone text,
    audience text,
    words integer not null default 0,
    read_time integer not null default 1,
    snippet text,
    content text not null default '',
    title_en text,
    snippet_en text,
    content_en text,
    title_ar text,
    snippet_ar text,
    content_ar text,
    created_at timestamptz not null default now()
);

-- Pastikan kolom multi-bahasa ada jika tabel sudah pernah dibuat sebelumnya
alter table public.articles add column if not exists title_en text;
alter table public.articles add column if not exists snippet_en text;
alter table public.articles add column if not exists content_en text;
alter table public.articles add column if not exists title_ar text;
alter table public.articles add column if not exists snippet_ar text;
alter table public.articles add column if not exists content_ar text;

-- Pastikan kolom id dapat menerima ID kustom jika tabel sebelumnya dibuat via Supabase Studio
do $$
begin
    if exists (
        select 1 from information_schema.columns 
        where table_schema = 'public' 
          and table_name = 'articles' 
          and column_name = 'id' 
          and is_identity = 'YES'
          and identity_generation = 'ALWAYS'
    ) then
        alter table public.articles alter column id set generated by default;
    end if;
end $$;

alter table public.articles enable row level security;
grant select on public.articles to anon, authenticated;
drop policy if exists "Public can read articles" on public.articles;
create policy "Public can read articles" on public.articles
    for select to anon, authenticated using (true);

create table if not exists public.article_requests (
    id bigint generated by default as identity primary key,
    title text not null,
    category text,
    theme text not null,
    tone text not null default 'santai',
    user_name text not null default 'Pengunjung Portal',
    user_phone text not null default '',
    created_at timestamptz not null default now()
);

-- Pastikan kolom baru tetap ada jika tabel article_requests sudah dibuat sebelumnya
alter table public.article_requests add column if not exists category text;
alter table public.article_requests add column if not exists theme text;
alter table public.article_requests add column if not exists tone text default 'santai';

alter table public.article_requests enable row level security;

create table if not exists public.donations (
    id bigint generated by default as identity primary key,
    sender_name text not null default 'Hamba Allah',
    amount numeric not null default 0,
    method text default 'DANA',
    status text not null default 'pending',
    notes text,
    created_at timestamptz not null default now()
);

alter table public.donations enable row level security;
drop policy if exists "Public insert donations" on public.donations;
create policy "Public insert donations" on public.donations for insert to anon with check (true);
drop policy if exists "Public read donations" on public.donations;
create policy "Public read donations" on public.donations for select to anon using (true);

-- Muat ulang schema cache PostgREST Supabase
notify pgrst, 'reload schema';